builds:
  - binary: pno
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: pno
    url_template: https://github.com/dominikwinter/pno/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    homepage: https://github.com/dominikwinter/pno
    description: Generate and validate a Swedish Personnummer, an individualized identifier assigned to each individual born in Sweden
    license: MIT
    repository:
      owner: dominikwinter
      name: homebrew-tap
      branch: master

checksum:
  name_template: checksum.txt
