builds:
  - binary: pno
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: pno
    homepage: https://github.com/dominikwinter/pno
    tap:
      owner: dominikwinter
      name: homebrew-tap

checksum:
  name_template: checksum.txt
